<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_3</name>
   <tag></tag>
   <elementGuidId>8822dad8-ce46-4612-8e6d-a4fa8df24b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='productTable']/tbody/tr[3]/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productTable > tbody > tr:nth-of-type(3) > td:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;3 Tablet $5.99&quot;i] >> internal:role=cell >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>549da4e7-f566-455e-840a-3b7ed9464e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productTable&quot;)/tbody[1]/tr[3]/td[4]</value>
      <webElementGuid>e151e603-600b-47c0-8e1f-35ac271abed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='productTable']/tbody/tr[3]/td[4]</value>
      <webElementGuid>72615aad-ca5a-4e2e-b038-7c482c40bd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$5.99'])[1]/following::td[1]</value>
      <webElementGuid>8f167f38-828a-47b5-8a21-0e0a76893567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tablet'])[1]/following::td[2]</value>
      <webElementGuid>1cee20e0-8bc5-43e0-a632-995b905af253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smartwatch'])[1]/preceding::td[2]</value>
      <webElementGuid>a6eb3f0d-3342-4832-8539-d1734c132fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$7.99'])[1]/preceding::td[3]</value>
      <webElementGuid>8cbf8644-e9be-4fd8-9878-905958a72a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/table/tbody/tr[3]/td[4]</value>
      <webElementGuid>4115e473-a537-4a76-80b0-7990a98f17fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
