<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary_Skip to content_header__icon header_61881e</name>
   <tag></tag>
   <elementGuidId>5778be1d-f5e5-43ba-9a0f-c624a6b8b8ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//details[@id='Details-menu-drawer-container']/summary</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>summary.header__icon.header__icon--menu.header__icon--summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;header-top-left&quot;] >> internal:label=&quot;Menu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>ceef1ef1-dbe5-444b-a558-9183807b6540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c179d9bc-649a-4140-865a-225624ea5d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>63f224a3-3045-473f-9cb9-e390b96f5036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__icon header__icon--menu header__icon--summary</value>
      <webElementGuid>9dccc233-7d6b-4c44-b0e4-e6855c601fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>a8b1a69c-f472-45fe-85fd-3491e1f3a1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>on:click</name>
      <type>Main</type>
      <value>/toggle</value>
      <webElementGuid>2be9ffdc-bfce-421f-92c3-01fcf4ecdc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bd3912aa-4616-4873-b784-97c2773813a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Details-menu-drawer-container&quot;)/summary[@class=&quot;header__icon header__icon--menu header__icon--summary&quot;]</value>
      <webElementGuid>3567101b-ccf2-46dc-8c88-2ada7fb7012b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//details[@id='Details-menu-drawer-container']/summary</value>
      <webElementGuid>0b25784e-a06a-4537-bbc8-cd1c737193d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to content'])[1]/following::summary[1]</value>
      <webElementGuid>7c0984cf-5497-4c38-8c0b-6fdc426d22c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Arrivals'])[1]/preceding::summary[1]</value>
      <webElementGuid>7097b634-f8bc-42d6-b990-250109aedcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kanchipuram'])[1]/preceding::summary[1]</value>
      <webElementGuid>0e44ee00-2021-4f3d-ab77-0a2d7c91e644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//summary</value>
      <webElementGuid>9aedfcb3-a576-4785-ac17-a9deb6d0ff7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
