<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>af81a609-85a9-4e1c-8e3b-d6ca7ac260be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='HeaderMenu-MenuList-1']/li/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;MyneeMoe stainless steel office lunch box with bag&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#HeaderMenu-MenuList-1 >> internal:role=link[name=&quot;MyneeMoe stainless steel office lunch box with bag Lunch Box&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>be2493d5-10ca-4f3a-9e82-73c23d4c264b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//myneemoe.in/cdn/shop/collections/Buy_Lunch_Boxes_Tiffin_Boxes_Online.webp?v=1744807216</value>
      <webElementGuid>b932fad1-752d-4342-ac38-f0d4c91d9049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MyneeMoe stainless steel office lunch box with bag</value>
      <webElementGuid>07a53c28-684c-4bcb-8ebb-6d9e2dee1167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>cc7f26ab-ef70-4724-a61f-dc7487745c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>e4dd15b5-f6d6-4191-83a1-d5567769e677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HeaderMenu-MenuList-1&quot;)/li[1]/a[1]/img[1]</value>
      <webElementGuid>b8dc0765-38d9-41c3-916a-48c79cab06e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='HeaderMenu-MenuList-1']/li/a/img</value>
      <webElementGuid>10a42abd-4418-451d-abc1-4f6aef673463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='MyneeMoe stainless steel office lunch box with bag']</value>
      <webElementGuid>56015f86-f61d-44e3-ae02-e4809315a4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details/ul/li/a/img</value>
      <webElementGuid>779e0922-e91e-4763-b408-ce0c27b51398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//myneemoe.in/cdn/shop/collections/Buy_Lunch_Boxes_Tiffin_Boxes_Online.webp?v=1744807216' and @alt = 'MyneeMoe stainless steel office lunch box with bag']</value>
      <webElementGuid>0dc86cb5-34e4-4bb3-b432-204e1d6d19c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
