<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>12221d53-c2d4-4f90-b1d8-e9774aa3ec9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//summary[@id='HeaderMenu-shop-by-product']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HeaderMenu-shop-by-product > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Shop By Product MyneeMoe Website Caret&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b9d4592e-f0b1-4fa6-9b79-cbd4ab78c9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop By Product</value>
      <webElementGuid>74f93f94-2815-41fb-8932-334e78f9977e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HeaderMenu-shop-by-product&quot;)/span[1]</value>
      <webElementGuid>e14438ca-6e33-47a5-8491-06e4fc01b34c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//summary[@id='HeaderMenu-shop-by-product']/span</value>
      <webElementGuid>33c3a721-ae99-4a1b-85d9-39d5133517e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyneeMoe Website Close Icon'])[5]/following::span[1]</value>
      <webElementGuid>96cfb1a9-b239-450e-a4d2-e0283bdc1a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyneeMoe Website Search Icon'])[1]/following::span[3]</value>
      <webElementGuid>54a37161-f7f8-4674-b5d3-724097200bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyneeMoe Website Caret Icon'])[3]/preceding::span[1]</value>
      <webElementGuid>ebdd34f5-c0c9-4a28-8ef8-d0139eae9094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lunch Box'])[2]/preceding::span[1]</value>
      <webElementGuid>5d73f3f3-d78e-4aca-a576-06984e1ce68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header-menu/details/summary/span</value>
      <webElementGuid>17ccf0c0-076a-4442-9c88-d7bd64cadfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Shop By Product' or . = 'Shop By Product')]</value>
      <webElementGuid>44e0b9bc-3ead-41f9-9387-d472ecf9aae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
