<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Today_nav_home</name>
   <tag></tag>
   <elementGuidId>e160c67e-aebd-4069-ab92-e9d6e3d90551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;nav_home&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='nav_home']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#home >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>10e31985-eb37-469c-a6d8-5e747a841f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nav_home</value>
      <webElementGuid>0feccb8f-9c9e-456f-ad18-3f20a7afc2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./img/nav_home2.gif</value>
      <webElementGuid>dc5a0297-1c3b-483f-914c-66bb760094e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>88</value>
      <webElementGuid>aa97f6ca-993e-4250-8f6b-7fc3ac247a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>4b51b0fc-3cad-4ff8-bc60-4686f534e744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>44838af3-9ead-4621-81a3-68745f1e6a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>f519c7e8-f45a-4490-9062-e7f738abb3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/a[1]/img[1]</value>
      <webElementGuid>b2e983a8-8135-44af-8f29-ccb602fc1ff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='nav_home']</value>
      <webElementGuid>0f1f6b33-a6c4-4834-91f4-18b10b4d266d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='home']/a/img</value>
      <webElementGuid>28ca131d-4bf6-4fad-975b-836e68202c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/img</value>
      <webElementGuid>4d953af9-d064-4603-962f-4305a0c62484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'nav_home' and @src = './img/nav_home2.gif']</value>
      <webElementGuid>59b8ca34-383a-4421-bb96-1cf7e6865a45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
