<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Today_headline</name>
   <tag></tag>
   <elementGuidId>217d577e-a927-4c6e-b22d-77ce8fd6c7f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.headline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='main']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Welcome to CityLights&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>978941a0-5ea7-4741-b6fe-97f21020ce29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headline</value>
      <webElementGuid>d8a5cb38-59f3-4302-bed9-52988b638113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome to CityLights</value>
      <webElementGuid>5c8d9da1-c620-4afd-b68e-6ae4bd0682b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/p[@class=&quot;headline&quot;]</value>
      <webElementGuid>4a69c584-cf85-4abe-b627-e04af362b3f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='main']/p</value>
      <webElementGuid>cf246e15-8681-4406-9ade-1390bf3ea460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today:'])[1]/following::p[1]</value>
      <webElementGuid>23c44fb3-7c07-4cc1-a6ba-2c24bce1f906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Heat wave linked to temperatures'])[1]/preceding::p[2]</value>
      <webElementGuid>f813ab1b-f16d-41d1-afec-48ea0a8b8f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Man Gets Nine Months in Violin Case'])[1]/preceding::p[2]</value>
      <webElementGuid>ea0f39e9-5049-466c-aa71-2857204a3c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome to CityLights']/parent::*</value>
      <webElementGuid>7c9abfbc-7310-4704-b02e-729a9558b68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/p</value>
      <webElementGuid>f36d677c-9386-47e8-9f94-9c5858bbc75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Welcome to CityLights' or . = 'Welcome to CityLights')]</value>
      <webElementGuid>b1129930-141e-45c7-859c-efdd3a0ceb21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
