<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>dda50c92-9297-4957-8cee-0f95a91747b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[3]/article/div/div/section/div/div/div/div/div[3]/a/div/div/div/div/div[3]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slick-slide.slick-active.slick-current > div > img[alt=&quot;Regal Radiance Pendant&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Regal Radiance Pendant&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>76f5ea57-6447-4714-b99e-6c2efd03b48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Regal Radiance Pendant</value>
      <webElementGuid>60dbf9b4-5d1e-4bd6-b639-c59e6f0ff050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>classes</name>
      <type>Main</type>
      <value>images-image-05j image-image-f-I</value>
      <webElementGuid>c4d01e57-591d-497e-8ed1-fae80b8127db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.joyalukkas.in/media/catalog/product/d/s/dsnp00000125_2.jpg?tr=w-360</value>
      <webElementGuid>0b32aa0a-385d-4e1c-bf39-b302d125d0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>7b38841e-56ee-4dd1-8278-87d48baa8b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>5987f053-b0f3-4dea-a3ca-edea3695b801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>063f4850-1bc8-4653-927f-ba9e5a5146e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>870ac12e-0f94-4cf6-8b16-c1408e327ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-YLm bg-white relative text-colorDefault&quot;]/div[@class=&quot;main-page-hXb max-w-site mx-auto my-0&quot;]/article[@class=&quot;category-root-Zmt&quot;]/div[1]/div[1]/section[1]/div[@class=&quot;gallery-root-MY9 my-4 mx-auto px-2 w-full lg_px-[40px]&quot;]/div[@class=&quot;gallery-items-kMz grid grid-cols-2 sm_grid-cols-3 xl_grid-cols-4 sm_gap-xs gap-2&quot;]/div[@class=&quot;item-root-NyK relative grid min-w-full staticRoot&quot;]/div[@class=&quot;item-rootInner-4Im grid&quot;]/div[@class=&quot;item-imageWrap-VV4 mb-2xs&quot;]/a[@class=&quot;item-images-Or3 grid&quot;]/div[@class=&quot;item-itemSlider-b1z&quot;]/div[@class=&quot;slick-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/img[1]</value>
      <webElementGuid>95f8394e-a044-4592-846d-2448e1ba0aef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/article/div/div/section/div/div/div/div/div[3]/a/div/div/div/div/div[3]/div/img</value>
      <webElementGuid>56401715-afc1-4503-b9cb-803acf4375fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Regal Radiance Pendant'])[3]</value>
      <webElementGuid>4d0d29d1-fe47-4818-854d-a5e9439e322d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>6973185b-e8df-42d4-b265-e161da300308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Regal Radiance Pendant' and @src = 'https://cdn.joyalukkas.in/media/catalog/product/d/s/dsnp00000125_2.jpg?tr=w-360']</value>
      <webElementGuid>184600d5-2e81-4437-9bf4-c3c0238ad9f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
