<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_India Travel_elementor-animation-grow a_3e29e6</name>
   <tag></tag>
   <elementGuidId>70bd064b-b66d-4802-a350-2bfbe7348c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-7091']/div/div/section[2]/div/div/div/section/div/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.elementor-animation-grow.attachment-large.size-large.wp-image-7099</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hornbill Festival tour Package&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f473bf58-0d35-4f3f-901a-cf1fc24c5b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>8eee22e7-5aba-4062-94c1-3d9ad8a07ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b54bda96-001e-482c-8b70-d04577259254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>43bf0447-cb20-413a-a9d1-186c4169091d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>700</value>
      <webElementGuid>a617dcd3-cb62-4797-b08e-9b86638711e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/indiatravel.com/wp-content/uploads/2024/04/Hornbill-Festival-Package.webp?fit=500%2C700&amp;ssl=1</value>
      <webElementGuid>9738c171-a10e-4de5-bbe3-572457eb304d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-animation-grow attachment-large size-large wp-image-7099</value>
      <webElementGuid>86793023-df22-456a-807a-2c53a083383f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hornbill Festival tour Package</value>
      <webElementGuid>e42f10dd-4a5b-4831-bec8-f6e638a7edf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://i0.wp.com/indiatravel.com/wp-content/uploads/2024/04/Hornbill-Festival-Package.webp?w=500&amp;ssl=1 500w, https://i0.wp.com/indiatravel.com/wp-content/uploads/2024/04/Hornbill-Festival-Package.webp?resize=214%2C300&amp;ssl=1 214w</value>
      <webElementGuid>9b8774aa-c621-44f8-9ec5-947ef6db24b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 500px) 100vw, 500px</value>
      <webElementGuid>e4b3a78c-e0f9-48cd-84cc-248483de9376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-7091&quot;)/div[@class=&quot;entry-content clear&quot;]/div[@class=&quot;elementor elementor-7091&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-e48dfea elementor-section-boxed elementor-section-height-default elementor-section-height-default wpr-particle-no wpr-jarallax-no wpr-parallax-no wpr-sticky-section-no&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-139a5fc&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/section[@class=&quot;elementor-section elementor-inner-section elementor-element elementor-element-d9ab1a5 elementor-section-boxed elementor-section-height-default elementor-section-height-default wpr-particle-no wpr-jarallax-no wpr-parallax-no wpr-sticky-section-no&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-20c209d&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-908e0ad elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;elementor-animation-grow attachment-large size-large wp-image-7099&quot;]</value>
      <webElementGuid>de4b4c0a-5d9c-48b1-be54-ae1890b4867b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-7091']/div/div/section[2]/div/div/div/section/div/div/div/div/div/a/img</value>
      <webElementGuid>51525b9d-b645-4e70-ac1c-d81f19ee2e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hornbill Festival tour Package']</value>
      <webElementGuid>a2890bdd-0064-4304-95c1-ec70b7f8ea9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>0a7f775a-510c-43d5-b36c-7cec5c63a925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/indiatravel.com/wp-content/uploads/2024/04/Hornbill-Festival-Package.webp?fit=500%2C700&amp;ssl=1' and @alt = 'Hornbill Festival tour Package']</value>
      <webElementGuid>8fc94874-b030-4694-9424-b3a3a3a54eeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
