<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Safari Bags_header__logo-image</name>
   <tag></tag>
   <elementGuidId>b5391f33-34ad-41cd-ad48-240e2f9bc019</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-header']/store-header/div/div/h1/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.header__logo-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Safari Bags&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3a43473c-ff94-43d9-979f-113478ad089a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__logo-image</value>
      <webElementGuid>ffc391d9-1631-4a06-84b0-38b7671fabdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>537</value>
      <webElementGuid>06e93f6c-646c-44c6-aeeb-166951dc48c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>160</value>
      <webElementGuid>a02fa295-2fae-4f45-ba7a-67a53d1cd2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//safaribags.com/cdn/shop/files/safari_logo_160x.png?v=1701758679</value>
      <webElementGuid>599e1003-91ab-4124-811e-8243d518f6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-header&quot;)/store-header[@class=&quot;header header--bordered&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;header__wrapper&quot;]/h1[@class=&quot;header__logo&quot;]/a[@class=&quot;header__logo-link&quot;]/img[@class=&quot;header__logo-image&quot;]</value>
      <webElementGuid>2528ea5a-8994-4740-9479-38c97d40ead7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-header']/store-header/div/div/h1/a/img</value>
      <webElementGuid>4cb0394a-18b5-4d5f-be77-f57c3296663b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>dce6e307-1017-451f-909a-60a5cf265b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//safaribags.com/cdn/shop/files/safari_logo_160x.png?v=1701758679']</value>
      <webElementGuid>904bcdee-f161-4c0c-9fc4-570547913079</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
