<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Account  Lists_nav-flyout-button nav_5aa243</name>
   <tag></tag>
   <elementGuidId>25ba47c2-b8a3-44d8-b81d-2a9291a0503e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-link-accountList']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.nav-flyout-button.nav-icon.nav-arrow.nav-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Expand Account and Lists&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50f0cd9b-8f32-47c3-9a07-97952faf9387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-flyout-button nav-icon nav-arrow nav-active</value>
      <webElementGuid>94aaa8a3-c074-4368-8208-04bbeb6c9fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Expand Account and Lists</value>
      <webElementGuid>0cc75882-0af0-4335-9344-b7abcb485110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>481e34ad-ce6a-4600-9df3-7d4f372d8692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>46c38762-9aa7-4c6f-b403-29f839704dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-link-accountList&quot;)/button[@class=&quot;nav-flyout-button nav-icon nav-arrow nav-active&quot;]</value>
      <webElementGuid>f9b0b948-f92b-48fd-82d8-b01cb1775824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-link-accountList']/button</value>
      <webElementGuid>da45843f-75ad-41b5-b9a6-080a933269ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>fae42ae2-fb26-409d-abe4-7b52a57f88c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
