<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_landing page_pill2 pill2--white-dark</name>
   <tag></tag>
   <elementGuidId>91a48eca-31ca-478a-a12d-caa0710c7e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrap']/div/div/section/div[3]/div/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;e-commerce&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f6e5cca-84ec-4ff2-af55-3969bf39d739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/e-commerce</value>
      <webElementGuid>9f748640-a9c2-4cba-abb2-f9a344acb426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pill2 pill2--white-dark</value>
      <webElementGuid>4d35888c-be8f-4fce-9e97-9be90a13e66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    e-commerce
                  </value>
      <webElementGuid>fa5e751a-0dd6-4eef-a06c-6a6efb7d6c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap&quot;)/div[@class=&quot;home-hero container2&quot;]/div[@class=&quot;home-hero__content-container&quot;]/section[@class=&quot;home-hero__search-container&quot;]/div[@class=&quot;home-hero__trending-container&quot;]/div[@class=&quot;home-hero__trending-scroll-container&quot;]/div[1]/a[@class=&quot;pill2 pill2--white-dark&quot;]</value>
      <webElementGuid>5a815784-d2ea-4f15-b45d-80ec495c916d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrap']/div/div/section/div[3]/div/div/a[3]</value>
      <webElementGuid>8f38a355-5e08-4688-bfc7-5cded058249f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'e-commerce')]</value>
      <webElementGuid>0909d964-b4a5-42b9-bff6-d52988bf6ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='landing page'])[1]/following::a[1]</value>
      <webElementGuid>aecef8fe-41f2-44e7-b2b9-b397c0b32697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dashboard'])[1]/following::a[2]</value>
      <webElementGuid>7fbddaa4-9630-4808-ba7a-3cd08032bdf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logo'])[1]/preceding::a[1]</value>
      <webElementGuid>0b57d53f-9c62-4a7d-81ff-44d54c5f8b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='card'])[1]/preceding::a[2]</value>
      <webElementGuid>e967c0b8-18f7-4397-aed9-d68aaa49d94b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='e-commerce']/parent::*</value>
      <webElementGuid>ac02ae08-aa76-4351-b995-702f96bab720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/e-commerce')]</value>
      <webElementGuid>d846533e-f6eb-4141-a1b7-9e36fdef0473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>227daf9d-d7c2-4583-8065-585de6d7c544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/e-commerce' and (text() = '
                    e-commerce
                  ' or . = '
                    e-commerce
                  ')]</value>
      <webElementGuid>a6a6dd33-1d6f-4ea6-8248-11b98d3dcf8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
