<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>bc6dc7ab-e8ed-4739-94a7-d9cca6c38be1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main_menu']/ul/li[7]/div/ul/li/ul/li/div/div[2]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12.col-lg > ul.cl-sub-menu-items > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Gold&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e28f152-6609-4ecf-8b4b-4213f9a382d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.kalyanjewellers.net/Jewellery/Gold/</value>
      <webElementGuid>cca52fd1-a97f-4cb6-9f8b-da31f6d8c856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gold</value>
      <webElementGuid>b50982ee-ef57-4fa0-bc8e-11052c4da19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_menu&quot;)/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item mr-auto&quot;]/div[@class=&quot;do-secondary-menu&quot;]/ul[1]/li[@class=&quot;cl-sub-menu&quot;]/ul[1]/li[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg&quot;]/ul[@class=&quot;cl-sub-menu-items&quot;]/li[1]/a[1]</value>
      <webElementGuid>aa934ff7-67a2-40a1-b10b-f0ab282af072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_menu']/ul/li[7]/div/ul/li/ul/li/div/div[2]/ul/li/a</value>
      <webElementGuid>7297f395-e14a-4731-8492-4dd5e03cba30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Gold')])[2]</value>
      <webElementGuid>d5a3f7f2-3880-421b-8c87-58cbb64f153b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metals'])[1]/following::a[1]</value>
      <webElementGuid>966d7767-23d1-4cc2-8cdd-4f953bc0e436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second stud'])[1]/following::a[1]</value>
      <webElementGuid>dc1f0dc0-3e7f-44c9-851c-5b7a7364168d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diamond'])[1]/preceding::a[1]</value>
      <webElementGuid>982c4127-468e-422a-94cc-1a0d128842cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silver'])[1]/preceding::a[2]</value>
      <webElementGuid>77a2e897-359e-43a0-9515-0517583bf3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gold']/parent::*</value>
      <webElementGuid>099dbbf5-ea66-4c6d-9a79-4144341cd510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.kalyanjewellers.net/Jewellery/Gold/')])[4]</value>
      <webElementGuid>e3e3c87b-3730-47a0-a3e6-057448231a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]/ul/li/a</value>
      <webElementGuid>77944776-a7fd-4710-abbc-a336ee2f6136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.kalyanjewellers.net/Jewellery/Gold/' and (text() = 'Gold' or . = 'Gold')]</value>
      <webElementGuid>886bc5c5-c641-4484-bbd7-032c9ebe2acf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
