<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact Us_wpr-slider-secondary-btn</name>
   <tag></tag>
   <elementGuidId>04a3c9d0-6a16-4794-894c-4de2694b6dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide00']/div/div/div[3]/div/div/div/div[3]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.wpr-slider-item.elementor-repeater-item-c86ca1e > div.wpr-cv-container > div.wpr-cv-outer > div.wpr-cv-inner > div.wpr-slider-content > div.wpr-slider-btns > a.wpr-slider-secondary-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#slick-slide00 >> internal:role=link[name=&quot;Packages&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52808c15-4e06-403a-9072-77f6631a8a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpr-slider-secondary-btn</value>
      <webElementGuid>83d9b532-29ab-44b1-854a-a58594cd355a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://indiatravel.com/tours/</value>
      <webElementGuid>a877ee07-a5e6-41a3-b976-b72708e25728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>95bdec0c-1b12-4677-9aaa-002f27f9fb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Packages</value>
      <webElementGuid>d545a1a2-f056-470a-93f5-9c6b3cd41657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide00&quot;)/div[1]/div[@class=&quot;wpr-slider-item elementor-repeater-item-c86ca1e&quot;]/div[@class=&quot;wpr-cv-container&quot;]/div[@class=&quot;wpr-cv-outer&quot;]/div[@class=&quot;wpr-cv-inner&quot;]/div[@class=&quot;wpr-slider-content&quot;]/div[@class=&quot;wpr-slider-btns&quot;]/a[@class=&quot;wpr-slider-secondary-btn&quot;]</value>
      <webElementGuid>ebfae1c8-20c6-4da1-8251-7e5893b4951b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide00']/div/div/div[3]/div/div/div/div[3]/a[2]</value>
      <webElementGuid>73cbcc66-bf42-4455-9e8e-2b7563f83a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Packages')])[3]</value>
      <webElementGuid>27a98020-73fd-4190-8dc8-6a2cd0df02cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/following::a[1]</value>
      <webElementGuid>2c1df38b-fe7e-43a8-b873-0de6f9f82912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore India with Our Package'])[3]/preceding::a[1]</value>
      <webElementGuid>acf33595-a400-4e80-9d67-52a001d69639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experience Luxury Trains of India'])[1]/preceding::a[1]</value>
      <webElementGuid>bd3a57ff-1096-456d-98da-e1768600918c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://indiatravel.com/tours/')])[2]</value>
      <webElementGuid>9c380cbe-3806-4608-bf5a-e939096dc561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/div/div[3]/a[2]</value>
      <webElementGuid>5ba57bc6-2f8e-4dbe-bd9d-314d0271b40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://indiatravel.com/tours/' and (text() = 'Packages' or . = 'Packages')]</value>
      <webElementGuid>f8473daa-5978-43d6-9b0c-f89de77a1006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
