<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Packages_menu-link</name>
   <tag></tag>
   <elementGuidId>a25d85f6-91ff-4c04-94b9-0106ebc68cb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-7103']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-7103 > a.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Festival Tour&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6bda25f6-d964-4094-9cba-bb5ac1dd80b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://indiatravel.com/festival-tour/</value>
      <webElementGuid>7e4520b2-1323-42ac-9e2e-d5281598f814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>81b35df8-e6cf-435a-82f0-4712024bd73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Festival Tour</value>
      <webElementGuid>d3c1537f-1f9c-4edc-b458-01558790f8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-7103&quot;)/a[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>e13ce22f-9e12-4889-a981-eba6a2180776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-7103']/a</value>
      <webElementGuid>9ec3fe3a-f227-43a4-bfaa-2a4e259cfed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Festival Tour')]</value>
      <webElementGuid>85c833b1-e220-42f3-a84e-5e62c06f30a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packages'])[1]/following::a[1]</value>
      <webElementGuid>21fb5b29-e5a3-4a71-a2b6-70b82eb8b09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destinations'])[1]/following::a[2]</value>
      <webElementGuid>aa963045-2bd9-4b61-b80d-f4ac14e4a3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilgrimage India'])[1]/preceding::a[1]</value>
      <webElementGuid>3c957064-0bf6-4b41-a528-08970d365f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu Toggle'])[1]/preceding::a[3]</value>
      <webElementGuid>813b7202-0cb3-43fd-98ce-6421bc7365c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Festival Tour']/parent::*</value>
      <webElementGuid>4f267de8-e053-450a-85ad-5d251f0b8c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://indiatravel.com/festival-tour/')]</value>
      <webElementGuid>7b5fed24-dabe-4169-b9fa-4608d5271dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>0fcb4c1d-6170-4909-ad55-d25e5da2c27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://indiatravel.com/festival-tour/' and (text() = 'Festival Tour' or . = 'Festival Tour')]</value>
      <webElementGuid>c89c8b20-f7b1-4016-8ca8-da26dfdea936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
