<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Vertical slider_demo-frame</name>
   <tag></tag>
   <elementGuidId>7607168b-9da4-42fd-bf70-6fbd1d0c0934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.demo-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ba2e874c-deeb-4a79-998a-3e112a8982d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/demos/slider/default.html</value>
      <webElementGuid>460d9d3d-5f41-4de4-adfa-4585b5adee1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-frame</value>
      <webElementGuid>9ade5831-6b5e-4c0c-8923-77e458a0b40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/iframe[@class=&quot;demo-frame&quot;]</value>
      <webElementGuid>d648ef45-e85f-4738-bfe6-86114923bff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/iframe</value>
      <webElementGuid>200f9260-4d28-49a5-b588-543f2a1540ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a3b2342e-1ac1-44d7-a856-287f83e8867c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/resources/demos/slider/default.html']</value>
      <webElementGuid>49bc8c3e-50fc-4409-aa9b-fb3436043af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
