<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KIDS_navigation__link</name>
   <tag></tag>
   <elementGuidId>523f60a9-952e-493c-a655-66901eec359b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-nav']/div/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;NEW ARRIVALS&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d44a1373-957d-4b79-aec5-e66e9cbdb97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/collections</value>
      <webElementGuid>6106d5b1-985b-4b14-ba34-fc155c854cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navigation__link</value>
      <webElementGuid>84965b55-c29a-4751-a9ba-528b0a218512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEW ARRIVALS</value>
      <webElementGuid>c7f90062-73c1-48c8-a0ef-7ac61fbb6415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/div[@class=&quot;navigation navigation--main asas&quot;]/div[@class=&quot;navigation__tier-1-container test&quot;]/ul[@class=&quot;navigation__tier-1&quot;]/li[@class=&quot;navigation__item&quot;]/a[@class=&quot;navigation__link&quot;]</value>
      <webElementGuid>5c84c08e-023c-4146-8c59-b4e49996419f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-nav']/div/div/ul/li[2]/a</value>
      <webElementGuid>1b83c5ee-8a49-42f8-b1ea-34fde78e74c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'NEW ARRIVALS')])[2]</value>
      <webElementGuid>e01ea08b-32ed-497d-88d2-1e82f5730e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KIDS'])[2]/following::a[1]</value>
      <webElementGuid>ea537aee-19fd-4443-a452-28c231a5bc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WOMEN'])[2]/following::a[2]</value>
      <webElementGuid>e6f63099-0762-49c0-9a86-abf8ff8edb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEN'])[3]/preceding::a[1]</value>
      <webElementGuid>5151512c-cf04-44e4-84c5-5b8567bea959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shoes'])[1]/preceding::a[3]</value>
      <webElementGuid>7bfd26ab-0f6c-4247-8b17-9c4b23eefe7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/collections')])[3]</value>
      <webElementGuid>e380e8ff-fb9d-4b8f-ae10-23e8cba70e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>8a934943-3eab-43f3-8154-4492acb31ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/collections' and (text() = 'NEW ARRIVALS' or . = 'NEW ARRIVALS')]</value>
      <webElementGuid>1576c3d0-ae68-4ff0-b1c7-440a7e43b121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
