<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Menu Toggle_menu-link</name>
   <tag></tag>
   <elementGuidId>e8064f55-a157-4669-b400-7a878790a242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2484']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2484 > a.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Luxury Trains&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>34447109-930c-4627-8f2d-3055a6787bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://indiatravel.com/luxury-trains/</value>
      <webElementGuid>d11f7d06-e736-4335-bf9b-e927f3b70d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>076a7549-0c3a-4bfe-a191-a0bdee46bf3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Luxury Trains</value>
      <webElementGuid>cbd42277-b5e6-4b3c-accb-0a80fdbb92b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2484&quot;)/a[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>5a6a64d3-6043-402d-8fa3-161c4ccf81cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2484']/a</value>
      <webElementGuid>6d893708-143c-4980-83fd-c698bb7b5f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Luxury Trains')]</value>
      <webElementGuid>c5131d4f-3826-4fd4-8595-938dcc708ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu Toggle'])[1]/following::a[1]</value>
      <webElementGuid>8269db23-68d3-4953-b984-00fa6a381fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilgrimage India'])[1]/following::a[2]</value>
      <webElementGuid>ed703a67-7a13-4e0e-9323-e5ef8e9b0c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luxury Hotels'])[1]/preceding::a[1]</value>
      <webElementGuid>88fc3ce9-1ecc-4588-a491-864a92a2a90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blogs'])[1]/preceding::a[2]</value>
      <webElementGuid>30db6189-a640-4965-83b8-c9941396e90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Luxury Trains']/parent::*</value>
      <webElementGuid>4d839fb5-81f8-4358-9bcf-39ff951ec0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://indiatravel.com/luxury-trains/')]</value>
      <webElementGuid>086eb1f6-d6b9-493d-b398-de523f29da51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>0a5adc25-df91-4e8b-98fc-b70f4bab0610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://indiatravel.com/luxury-trains/' and (text() = 'Luxury Trains' or . = 'Luxury Trains')]</value>
      <webElementGuid>029ce31c-3688-401f-b107-ac1370fad65c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
