<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shop Online_nav-link parent</name>
   <tag></tag>
   <elementGuidId>44fd946c-c453-49dd-b36d-854f8543a90a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main_menu']/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Jewellery&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25f1535d-0c31-4372-ab27-6ce5b02adfb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link parent </value>
      <webElementGuid>16004f72-9035-474c-ba72-564b93aa594a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.kalyanjewellers.net/Jewellery/</value>
      <webElementGuid>cd8c1e1f-3b38-4d04-a1e8-e2734ab8c5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jewellery</value>
      <webElementGuid>bddfd464-3597-4c2f-aec0-601e9ada072a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_menu&quot;)/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item mr-auto&quot;]/a[@class=&quot;nav-link parent&quot;]</value>
      <webElementGuid>f4712531-cedc-4c33-b174-9d3dfb7ba3c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_menu']/ul/li[7]/a</value>
      <webElementGuid>02b4ca4b-5300-4e70-bc2f-76bdc98e2a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Jewellery')]</value>
      <webElementGuid>4c741bbd-f4da-418b-a839-4f3a4cd22d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Online'])[2]/following::a[1]</value>
      <webElementGuid>11bb75ba-6ebb-4fbf-9b87-abaeb6b37106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Andhra Pradesh &amp; Telangana'])[1]/following::a[2]</value>
      <webElementGuid>9de946be-b8d4-4588-a0df-a5233c687506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jewellery'])[2]/preceding::a[1]</value>
      <webElementGuid>63931d59-7184-4d8d-b9e2-628bf96694d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jewellery'])[3]/preceding::a[1]</value>
      <webElementGuid>09bf1906-0369-4fe3-babe-555c6b5d6599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jewellery']/parent::*</value>
      <webElementGuid>470e56d8-385d-44fe-8613-a553a825a785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.kalyanjewellers.net/Jewellery/')]</value>
      <webElementGuid>c3c8b51a-30a5-4ac7-bf27-e673538f2a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>67b5889f-42ec-4fbe-94b4-db3355dd9883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.kalyanjewellers.net/Jewellery/' and (text() = 'Jewellery' or . = 'Jewellery')]</value>
      <webElementGuid>483d861a-7798-4e09-81b5-b36246d07f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
